name: Deploy Release

on:
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout 🛎️
                uses: actions/checkout@v2.3.1

            -   name: Install and Build 🔧
                run: |
                    yarn install
                    yarn build
                    rm -rf .babelrc
                    rm -rf .eslintrc.js
                    rm -rf .github
                    rm -rf .gitignore
                    rm -rf .travis.yml
                    rm -rf _jstest
                    rm -rf _test
                    rm -rf node_modules
                    rm -rf package.json
                    rm -rf pre-commit.hook.sh
                    rm -rf requirements.txt
                    rm -rf script
                    rm -rf stylelint.config.js
                    rm -rf webpack.config.js
                    rm -rf yarn.lock

            -   name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@4.1.4
                with:
                    branch: release
                    folder: .
